project:
  type: website
  output-dir: docs
  render: 
    - "**/*.qmd"
    - "**/*.ipynb"
    - "!**/*.Rmd"

website:
  title: "CoastWatch Training"
  favicon: images/coastwatch.png

  page-footer: 
    left: "&copy; CC-By CoastWatch, 2026"

  # Left sidebar navigation
  sidebar:
    background: "#D9E3E8"
    logo: "images/coastwatch.png"
    favicon: "images/coastwatch.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://coastwatch.noaa.gov/cwn
    style: "docked"
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd

      - text: "News & Announcements"
        href: news-announcements.qmd

      - section: "Training Classes"
        href: trainings/index.qmd
        contents:
          - section: "Upcoming Trainings"
            contents:
              - href: trainings/upcoming/pgrsc26.qmd
                text: 2026 PGRSC Course
              - href: trainings/upcoming/sat201_26.qmd
                text: 2026 Satellite 201 Summer Series
          - section: "Past Trainings"
            contents:
              - href: trainings/past/icft25.qmd
                text: 2025 Satellite and Animal Telemetry
              - href: trainings/past/longislandsound25.qmd
                text: 2025 Long Island Sound
              - href: trainings/past/pgrsc24.qmd
                text: 2024 PGRSC Workshop
              - href: trainings/past/seaice24.qmd
                text: 2024 Sea Ice Data Course
              - href: trainings/past/afs24.qmd
                text: 2024 AFS Workshop

      - section: "Training Tutorials"
        href: tutorials/index.qmd
        contents:
          - href: tutorials/codegallery.qmd
            text: "Code Gallery"
          - section: "Software Tutorials"
            contents:
              - section: "Software Information"
                contents:
                - href: tutorials/erddap.qmd
                  text: ERDDAP
                - href: tutorials/netcdf-panoply.qmd
                  text: NetCDF and Panoply
                - href: tutorials/cwutils.qmd
                  text: CoastWatch Utilities

              - href: tutorials/software.qmd
                text: "Software Code Gallery"

      - text: "Course Lectures"
        href: lectures/index.qmd

      - text: "Office Hours"
        href: officehours.qmd

      - text: "About Us"
        href: about.qmd

      - text: "Help"
        href: help.qmd
  page-navigation: true


format:
  html:
    theme:
      cosmo
    toc: true
    css: styles.css

callout-appearance: simple 



