project:
  type: website
  output-dir: docs
  resources: 
    - "tutorials/**/*.ipynb"
    - "tutorials/**/*.Rmd"

website:
  title: "CoastWatch Training Materials"

  # Left sidebar navigation
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd

      - section: "Training Tutorials"
        contents: 
          - href: tutorials/index.qmd
            text: "Software Tutorials"
          - href: tutorials/codegallery.qmd
            text: "Code Gallery"

  navbar:
    right:
      - icon: github
        href: https://github.com/madrichardson/CoastWatch-Training-Tutorials

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: false
    css: styles.css



