project:
  type: website
  output-dir: docs

website:
  title: "CoastWatch Training Materials"

  # Left sidebar navigation
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd

      - section: "Training Tutorials"
        contents: 
          - href: tutorials/index.qmd
            text: "Software Tutorials"
          - href: tutorials/codegallery.qmd
            text: "Code Gallery"

  navbar:
    right:
      - icon: github
        href: https://github.com/madrichardson/CoastWatch-Training-Tutorials

format:
  html:
    include-in-header:
      - text: |
          <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
    theme:
      light: cosmo
      dark: darkly
    toc: false
    css: styles.css



